
package Views;

import Controllers.ClientesControllers;
import Controllers.ConfigControllers;
import Controllers.ProductosControllers;
import Models.ClienteDao;
import Models.Clientes;
import Models.ProductoDao;
import Models.Productos;
import Models.UsuarioDao;
import Models.Usuarios;


public class PanelAdmin extends javax.swing.JFrame {

    Usuarios us = new Usuarios();
    UsuarioDao usDao = new UsuarioDao();
    Clientes cl = new Clientes();
    ClienteDao clDao = new ClienteDao();
    Productos pro = new Productos();
    ProductoDao proDao = new ProductoDao();
        
    public PanelAdmin() {
        initComponents();
        ConfigControllers config = new ConfigControllers(this);
        ClientesControllers cliente = new ClientesControllers(cl, clDao, this);
        ProductosControllers productos = new ProductosControllers(pro, proDao, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupCliente = new javax.swing.JPopupMenu();
        jMenuItemEliminarCliente = new javax.swing.JMenuItem();
        jMenuItemReingresarCliente = new javax.swing.JMenuItem();
        jPopupProductos = new javax.swing.JPopupMenu();
        jMenuItemReingresarProd = new javax.swing.JMenuItem();
        jMenuItemEliminarProd = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNomCliente = new javax.swing.JTextField();
        txtApCliente = new javax.swing.JTextField();
        txtDirCliente = new javax.swing.JTextField();
        txtTelCliente = new javax.swing.JTextField();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        txtIdCliente = new javax.swing.JTextField();
        txtBuscarCliente = new javax.swing.JTextField();
        btnLimpiarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtArtProd = new javax.swing.JTextField();
        txtNombreProd = new javax.swing.JTextField();
        txtDescripcionProd = new javax.swing.JTextField();
        txtCompraProd = new javax.swing.JTextField();
        btnNuevoProd = new javax.swing.JButton();
        btnEditarProd = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtVentaProd = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtIdProd = new javax.swing.JTextField();
        btnLimpiarProd = new javax.swing.JButton();
        txtBuscarProd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProd = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableNV = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtArtNV = new javax.swing.JTextField();
        txtNombreNV = new javax.swing.JTextField();
        txtCantNV = new javax.swing.JTextField();
        txtPrecioNV = new javax.swing.JTextField();
        txtTotalNV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnGenerarNV = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        seleccionarCliente = new javax.swing.JComboBox<>();
        txtDescuento = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtIdNV = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCont = new javax.swing.JTable();
        btnCont = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelClientes = new javax.swing.JPanel();
        jLabelClientes = new javax.swing.JLabel();
        jPanelProductos = new javax.swing.JPanel();
        jLabelProductos = new javax.swing.JLabel();
        jPanelFacturas = new javax.swing.JPanel();
        jLabelFacturas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItemEliminarCliente.setText("Eliminar");
        jPopupCliente.add(jMenuItemEliminarCliente);

        jMenuItemReingresarCliente.setText("Reingresar");
        jPopupCliente.add(jMenuItemReingresarCliente);

        jMenuItemReingresarProd.setText("Reingresar");
        jPopupProductos.add(jMenuItemReingresarProd);

        jMenuItemEliminarProd.setText("Eliminar");
        jPopupProductos.add(jMenuItemEliminarProd);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Vladimir Script", 0, 64)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Bienvenido");
        jLabel27.setToolTipText("");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 350, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 950, 640));

        jTabbedPane1.addTab("Inicio", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Cliente"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel8.setText("Nombre");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 107, -1, -1));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel9.setText("Apellido");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 147, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel10.setText("Direccion");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 187, -1, -1));

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel11.setText("Telefono");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 227, -1, -1));
        jPanel11.add(txtNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 104, 71, -1));
        jPanel11.add(txtApCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 144, 71, -1));
        jPanel11.add(txtDirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 184, 71, -1));
        jPanel11.add(txtTelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 224, 71, -1));

        btnNuevoCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnNuevoCliente.setText("Nuevo");
        jPanel11.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 296, -1, -1));

        btnEditarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnEditarCliente.setText("Editar");
        jPanel11.add(btnEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 296, -1, -1));
        jPanel11.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 72, -1));
        jPanel11.add(txtBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 58, 71, -1));

        btnLimpiarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 10)); // NOI18N
        btnLimpiarCliente.setText("Limpiar");
        jPanel11.add(btnLimpiarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 261, -1, 17));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 200, 340));

        jTableCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Telefono", "Direccion", "Estado"
            }
        ));
        jTableCliente.setComponentPopupMenu(jPopupCliente);
        jScrollPane3.setViewportView(jTableCliente);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 24, 510, 530));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 950, 640));

        jTabbedPane1.addTab("Clientes", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Producto"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel3.setText("Articulo");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 92, -1, -1));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 132, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel5.setText("Descripcion");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 172, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel6.setText("Precio de");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 207, -1, -1));
        jPanel8.add(txtArtProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 89, 71, -1));
        jPanel8.add(txtNombreProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 129, 71, -1));
        jPanel8.add(txtDescripcionProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 169, 71, -1));
        jPanel8.add(txtCompraProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 229, 71, -1));

        btnNuevoProd.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnNuevoProd.setText("Nuevo");
        jPanel8.add(btnNuevoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 366, -1, -1));

        btnEditarProd.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnEditarProd.setText("Editar");
        jPanel8.add(btnEditarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 366, -1, -1));

        jLabel20.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel20.setText("Compra");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 232, -1, -1));
        jPanel8.add(txtVentaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 277, 71, -1));

        jLabel21.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel21.setText("Venta");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 291, 43, -1));

        jLabel22.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabel22.setText("Precio de");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 269, -1, -1));

        txtIdProd.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel8.add(txtIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 71, -1));

        btnLimpiarProd.setText("Limpiar");
        jPanel8.add(btnLimpiarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 325, -1, 18));

        txtBuscarProd.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel8.add(txtBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 49, 71, -1));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 200, 410));

        jTableProd.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Articulo", "Nombre", "Descripcion", "Compra", "Venta", "Estado"
            }
        ));
        jTableProd.setComponentPopupMenu(jPopupProductos);
        jScrollPane2.setViewportView(jTableProd);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 24, 510, 530));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 950, 640));

        jTabbedPane1.addTab("Productos", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jTableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Art", "Nombre", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableNV);
        if (jTableNV.getColumnModel().getColumnCount() > 0) {
            jTableNV.getColumnModel().getColumn(0).setMaxWidth(25);
            jTableNV.getColumnModel().getColumn(1).setMaxWidth(80);
            jTableNV.getColumnModel().getColumn(3).setMaxWidth(80);
            jTableNV.getColumnModel().getColumn(4).setMaxWidth(80);
            jTableNV.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 700, 390));

        jLabel12.setText("Articulo");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel13.setText("Precio");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel14.setText("Nombre");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel16.setText("Cantidad");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        txtArtNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtArtNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, -1));

        txtNombreNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtNombreNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 100, -1));

        txtCantNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtCantNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 100, -1));

        txtPrecioNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtPrecioNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 100, -1));

        txtTotalNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtTotalNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, -1));

        jLabel17.setText("Total");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        btnGenerarNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        btnGenerarNV.setText("Generar Venta");
        jPanel6.add(btnGenerarNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cliente");
        jLabel18.setOpaque(true);
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        seleccionarCliente.setEditable(true);
        seleccionarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(seleccionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 200, -1));

        txtDescuento.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        txtDescuento.setText("0");
        jPanel6.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 70, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Total");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 40, 20));

        jLabel26.setText("Descuento");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));

        txtTotal.setText("0000000");
        jPanel6.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 60, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 950, 640));

        txtIdNV.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jPanel6.add(txtIdNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 30, -1));

        jTabbedPane1.addTab("Nueva Venta", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Articulo", "Nombre", "Descripcion", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTableCont);
        if (jTableCont.getColumnModel().getColumnCount() > 0) {
            jTableCont.getColumnModel().getColumn(0).setMaxWidth(30);
            jTableCont.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 710, 490));

        btnCont.setText("Generar Lista");
        jPanel7.add(btnCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 530, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -70, 950, 640));

        jTabbedPane1.addTab("Contador", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 750, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Vladimir Script", 2, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Duo2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 190, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 72));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelClientes.setBackground(new java.awt.Color(255, 255, 255));

        jLabelClientes.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(102, 102, 102));
        jLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClientes.setText("Clientes");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanelProductos.setBackground(new java.awt.Color(255, 255, 255));

        jLabelProductos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        jLabelProductos.setForeground(new java.awt.Color(102, 102, 102));
        jLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProductos.setText("Productos");

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 50));

        jPanelFacturas.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFacturas.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        jLabelFacturas.setForeground(new java.awt.Color(102, 102, 102));
        jLabelFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFacturas.setText("Facturas");

        javax.swing.GroupLayout jPanelFacturasLayout = new javax.swing.GroupLayout(jPanelFacturas);
        jPanelFacturas.setLayout(jPanelFacturasLayout);
        jPanelFacturasLayout.setHorizontalGroup(
            jPanelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFacturasLayout.setVerticalGroup(
            jPanelFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFacturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Diseño sin título.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCont;
    public javax.swing.JButton btnEditarCliente;
    public javax.swing.JButton btnEditarProd;
    public javax.swing.JButton btnGenerarNV;
    public javax.swing.JButton btnLimpiarCliente;
    public javax.swing.JButton btnLimpiarProd;
    public javax.swing.JButton btnNuevoCliente;
    public javax.swing.JButton btnNuevoProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelClientes;
    public javax.swing.JLabel jLabelFacturas;
    public javax.swing.JLabel jLabelProductos;
    public javax.swing.JMenuItem jMenuItemEliminarCliente;
    public javax.swing.JMenuItem jMenuItemEliminarProd;
    public javax.swing.JMenuItem jMenuItemReingresarCliente;
    public javax.swing.JMenuItem jMenuItemReingresarProd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanelClientes;
    public javax.swing.JPanel jPanelFacturas;
    public javax.swing.JPanel jPanelProductos;
    private javax.swing.JPopupMenu jPopupCliente;
    private javax.swing.JPopupMenu jPopupProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTableCliente;
    public javax.swing.JTable jTableCont;
    public javax.swing.JTable jTableNV;
    public javax.swing.JTable jTableProd;
    public javax.swing.JComboBox<Object> seleccionarCliente;
    public javax.swing.JTextField txtApCliente;
    public javax.swing.JTextField txtArtNV;
    public javax.swing.JTextField txtArtProd;
    public javax.swing.JTextField txtBuscarCliente;
    public javax.swing.JTextField txtBuscarProd;
    public javax.swing.JTextField txtCantNV;
    public javax.swing.JTextField txtCompraProd;
    public javax.swing.JTextField txtDescripcionProd;
    public javax.swing.JTextField txtDescuento;
    public javax.swing.JTextField txtDirCliente;
    public javax.swing.JTextField txtIdCliente;
    public javax.swing.JTextField txtIdNV;
    public javax.swing.JTextField txtIdProd;
    public javax.swing.JTextField txtNomCliente;
    public javax.swing.JTextField txtNombreNV;
    public javax.swing.JTextField txtNombreProd;
    public javax.swing.JTextField txtPrecioNV;
    public javax.swing.JTextField txtTelCliente;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtTotalNV;
    public javax.swing.JTextField txtVentaProd;
    // End of variables declaration//GEN-END:variables

}